name: Minify
on:
  push:
    branches: [ website ]
  workflow_dispatch:
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install html-minifier
        run: npm install html-minifier@4.0.0
      - name: Minify HTML
        run: html-minifier --collapse-whitespace --minify-js true --process-scripts "application/ld+json" --minify-css true --input-dir . --output-dir . --file-ext html
      - name: Install css-minify
        run: npm install css-minify@2.0.0
      - name: Minify CSS
        run: |
          css-minify -d . -o .
          python py/rename-stylesheet.py
      - name: Install uglify-js
        run: npm install uglify-js@3.15.4
      - name: Minify JS
        run: |
          uglifyjs script.js --compress --output script.min.js
          python py/rename-js-script.py
      - name: git config
        run: |
          git config --global user.name "Minify bot"
          git config --global user.email "<>"
      - name: Commit changes
        continue-on-error: true
        run: |
          git add --all
          git commit -m "Minify"
      - name: git push
        run: git push origin website
