name: Minify
on:
  push:
    branches: [ website ]
  workflow_dispatch:
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install html-minifier
        run: npm install html-minifier -g
      - name: Minify HTML
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true --input-dir . --output-dir . --file-ext html
      - name: Install css-minify
        run: npm install css-minify -g
      - name: Minify CSS
        run: |
          css-minify -f style.css
          rm style.css
          cp "css-dist/style.css" "style.css"
          rm -r css-dist
      - name: Install uglify-js
        run: npm install uglify-js -g
      - name: Minify JS
        run: uglifyjs script.js --compress --output script.js
      - name: git config
        run: |
          git config --global user.name "Minify bot"
          git config --global user.email "<>"
      - name: Commit changes
        run: |
          git add --all
          git commit -m "Minify"
      - name: git push
        run: git push origin website
