name: Minify
on:
  push:
    branches: [ website ]
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install html-minifier
        run: npm install html-minifier -g
      - name: Minify index.html
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true index.html --output index.html
      - name: Minify 404.html
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true 404.html --output 404.html
      - name: Minify blog/all.html
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true blog/all.html --output blog/all.html
      - name: Minify profile/*
        run: |
          html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true profile/GitHub.html --output profile/GitHub.html
          html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true profile/hashnode.html --output profile/hashnode.html
          html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true profile/twitter.html --output profile/twitter.html
      - name: Minify projects/all.html
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true projects/all.html --output projects/all.html
      - name: Minify social/*
        run: |
          html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true social/Dev-community.html --output social/Dev-community.html
          html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true social/GitHub.html --output social/GitHub.html
          html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true social/Hashnode.html --output social/Hashnode.html
          html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true social/twitter.html --output social/twitter.html
      - name: git config
        run: |
          git config --global user.name "Minify bot"
          git config --global user.email "<>"
      - name: Commit changes
        run: |
          git add --all
          git commit -m "Minify"
      - name: git push
        run: git push origin website
