name: Minify
on:
  push:
    branches: [ website ]
  workflow_dispatch:
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Replace style tag with style.css contents and script tag with script.js contents.
        run: python py/replace.py
      - name: Install html-minifier
        run: npm install html-minifier@4.0.0 -g
      - name: Minify HTML
        run: html-minifier --collapse-whitespace --minify-js true --process-scripts "application/ld+json" --minify-css true --input-dir . --output-dir . --file-ext html
      - name: git config
        run: |
          git config --global user.name "Minify bot"
          git config --global user.email "<>"
      - name: Commit changes
        continue-on-error: true
        run: |
          git add --all
          git commit -m "Minify"
      - name: git push
        run: git push origin website
