name: Minify
on:
  push:
    branches: [ website ]
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install html-minifier
        run: npm install html-minifier -g
      - name: Minify index.html
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true index.html --output index.html
      - name: Minify 404.html
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true 404.html --output 404.html
      - name: Minify blog/*
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true --input-dir ./blog --output-dir ./blog --file-ext html
      - name: Minify profile/*
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true --input-dir ./profile --output-dir ./profile -file-ext html
      - name: Minify projects/*
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true ./projects --output ./projects
      - name: Minify social/*
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true --input-dir ./social --output-dir ./social -file-ext html
      - name: Minify icons8-credits.html
        run: html-minifier --collapse-whitespace --remove-comments --remove-tag-whitespace --minify-js true --minify-css true icons8-credits.html --output icons8-credits.html
      - name: git config
        run: |
          git config --global user.name "Minify bot"
          git config --global user.email "<>"
      - name: Commit changes
        run: |
          git add --all
          git commit -m "Minify"
      - name: git push
        run: git push origin website
